### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by gianroxas** [Shermaine98/projectTEK2#1]
https://drive.google.com/open?id=0B-v4mDsXCFh2MkY0T3BEbE5lem8

Timestamps, Uploaders, etc. are shown as undefined. Also, "Ok" button does not work

**Comment by Shermaine98** [comment]
@gianroxas  sure ka meron pa rin? specific lang ba for reject?

**Comment by Shermaine98** [comment]
@gianroxas  @gcla109  exisitng parin ba ito?
