### ISSUE TITLE
reports change db error

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#10]
- please change db name

**Comment by Shermaine98** [comment]
@gianroxas @gcla109   please test

**Comment by gianroxas** [comment]
Saan ito? Reports? Sa pag-gawang reports, internal reports, saan? Please elaborate

**Comment by Shermaine98** [comment]
creating of reports. ni change ko kasi db name.. sa new database so try gumawa ng reports if okay na hahaha @gianroxas  @gcla109
