### ISSUE TITLE
Create Education Demo

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#102]

**Comment by grcldq** [comment]
Di ko alam paano napupunta doon yung button pls try on yours @gianroxas  @Shermaine98 
![image](https://cloud.githubusercontent.com/assets/11292448/20516199/4a9fd612-b0d0-11e6-8625-603694b0cd20.png)
Education create report > analysis > yung sa common reports (enrollment in public and private elem schools, the third option) but ok naman sya sa first and second 

![image](https://cloud.githubusercontent.com/assets/11292448/20516216/65aff8a6-b0d0-11e6-9af7-64117493e4e7.png)

**Comment by grcldq** [comment]
then pag click ko nung button sa gilid ito nangyayari

![image](https://cloud.githubusercontent.com/assets/11292448/20516234/840d5b2c-b0d0-11e6-9c8e-5a731388e6f2.png)
