### ISSUE TITLE
Education: Number of Teachers Public

### ISSUE THREAD

**Issue by grcldq** [Shermaine98/projectTEK2#108]
Pag click ng edit button, walang total, check in red

![image](https://cloud.githubusercontent.com/assets/11292448/20515436/9f02f4e0-b0cc-11e6-8578-b39aec4ddc75.png)

**Comment by gianroxas** [comment]
@Shermaine98 kapag click ng edit button, walang TOTAL TEACHERS.

![1](https://cloud.githubusercontent.com/assets/19302850/20529394/eb6ab410-b10a-11e6-8087-41ae6d0b0fec.JPG)

**Comment by gianroxas** [comment]
Ok na to
