### ISSUE TITLE
Forum Layout - Home Page

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#11]
ginagaya ko ung parang sa https://stackoverflow.com/..

![screen shot 2016-10-01 at 9 32 36 pm](https://cloud.githubusercontent.com/assets/11243128/19014426/0b81ddf6-881f-11e6-83e2-5bfc48335af6.png)

NOTE: hindi pa gumagana ung like and report buttons. after maayos ung layout tska ko na sya papaganahin

**Comment by grcldq** [comment]
Will do this tom/monday
