### ISSUE TITLE
NUM TEACHERS - UPDATE

### ISSUE THREAD

**Issue by gianroxas** [Shermaine98/projectTEK2#112]
When I update a school, male and female was saved interchangeably.
![screen shot 2016-11-22 at 8 35 27 pm](https://cloud.githubusercontent.com/assets/19302850/20524063/5b6c18ca-b0f3-11e6-836c-911af1baa5bf.png)

![screen shot 2016-11-22 at 8 36 06 pm](https://cloud.githubusercontent.com/assets/19302850/20524074/707bc620-b0f3-11e6-9a80-c3839b61fa8d.png)

BUTTT!! WHEN I UPDATE IT AGAIN, It updates to the correct values. PM me for details

**Comment by grcldq** [comment]
Baka baliktad lang yung title sa taas?
