### ISSUE TITLE
IT admin account not working

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#13]
@gcla109  may nagalaw ka d2? nung ni add mo ung other sector? d ko kasi magets ano ung error tama naman pero mali ung imports ni it admin

![screen shot 2016-10-01 at 10 39 24 pm](https://cloud.githubusercontent.com/assets/11243128/19014760/fd8b1fba-8827-11e6-8ada-bcf876ad026c.png)

**Comment by grcldq** [comment]
Wala ako ginagalaw

**Comment by Shermaine98** [comment]
wait open pa din ito since hindi masolve d ba?

**Comment by Shermaine98** [comment]
please reopen if not solved.

**Comment by Shermaine98** [comment]
@gianroxas  nakita mo bakit?

**Comment by gianroxas** [comment]
Hindi ko nakita kung bakit. :(

**Comment by Shermaine98** [comment]
pero working na siya? right? @gianroxas
