### ISSUE TITLE
Hide printing DIV after file is saved

### ISSUE THREAD

**Issue by grcldq** [Shermaine98/projectTEK2#23]
API/JS USED: http://www.cloudformatter.com/CSS2Pdf.APIDoc.Usage

Hide printing DIV after file is saved
![image](https://cloud.githubusercontent.com/assets/11292448/19211565/08c4ffaa-8d72-11e6-9b73-b0b2ba8a8fd7.png)

![image](https://cloud.githubusercontent.com/assets/11292448/19211569/11082840-8d72-11e6-977a-842e2dc6f5d5.png)
(this one should be hidden na after madownload)
and function doneyet() should be loaded

PS.
Di ko pa pala mapaliit yung size nung chart photo sa pdf so lagpas sya. Ayaw gumawa ng container size (style: width blah)

**Comment by Shermaine98** [comment]
done further enahncement needed @gcla109
