### ISSUE TITLE
forum

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#24]
may nasira akong unting layout. sorry hahaha

done everything please test with diff accounts thanks

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19220599/aa2b25f8-8e63-11e6-9b56-946ef46ca2f0.png)
 ganito talaga siya? title lang lalabas?

![image](https://cloud.githubusercontent.com/assets/11292448/19220600/b4c24438-8e63-11e6-9958-efd4166216ae.png)
(hello should not be appearing)

![image](https://cloud.githubusercontent.com/assets/11292448/19220602/be819654-8e63-11e6-8d45-bffb64869a5f.png)
dapat lumalabas yung first (title)

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19220608/cf11110c-8e63-11e6-8087-24156f8b8b88.png)
di nawawala yung hello :(

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19220634/3eb1cccc-8e64-11e6-8ba1-621eee00fb83.png)

![image](https://cloud.githubusercontent.com/assets/11292448/19220638/61067a7a-8e64-11e6-9703-3a2d43d66083.png)
Clickable ba to dapat? if hindi disable na lang natin :)

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19220646/8f76da26-8e64-11e6-97fa-34f661f3ce2e.png)
Erroor upon clicking redirects me to http://localhost:8084/projectTEKFinal/ForumSpecificServlet?forumId=

**Comment by Shermaine98** [comment]
- ung sa search may problem pa ako dyan due to layouting.. feeling ko kasi hindi talga dapat siya sa side na yan. need kasi ayusin ung part ng td and tr ... so after na dun tsaka ko na siya aayusin @gcla109

**Comment by Shermaine98** [comment]
ung mga tags not clikable na siya then for the hot topic bug un so i will fix asap @gcla109

**Comment by Shermaine98** [comment]
@gcla109  ni dl mo ung new db?
