### ISSUE TITLE
IT accounts INTERNAL approval

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#27]
internal and external

**Comment by grcldq** [comment]
I'm going to fix this

**Comment by grcldq** [comment]
External has been fixed. Prooblem is internal...
![image](https://cloud.githubusercontent.com/assets/11292448/19221604/46da6e12-8e79-11e6-89bf-74abc4c116ec.png)

Yung select kasi isa lang yung ID so pag ginalaw ko yung sa baba magcchange din yung sa taas... (by javascript yaan) tapos yung approve all sana disabled muna at first til maclick niya lahat ng select/input

**Comment by grcldq** [comment]
tapos yung approve all method sa servlet, for external pa lang. di ko kasi alam paano niya makukuha if external or internal pa

**Comment by Shermaine98** [comment]
@gcla109 fix all jquery things. ung sa approve all ginawa ko na lng required so kahit iclick un nang d ni chachange ung itaas hindi parin papasok sa servlet.

d pa tapos ung servlet

**Comment by Shermaine98** [comment]
```
                                <input  style="display: block; margin: 0 auto; width: 12%;"  class="btn btn-success" type="submit" value="Approve All" onclick="${pageContext.request.contextPath}/Approvals?redirect=approvalAllInternal;" />
```

 not sure if this will work

**Comment by Shermaine98** [comment]
then if d  makukuha mo kung external or internal from this `redirect=approvalAllInternal` part `reuqest.getAttribute(redirect)`then if statements na lng

**Comment by Shermaine98** [comment]
please try to finish by sunday. gawin ko ung validation

**Comment by grcldq** [comment]
Pacheck, nafix ko na yung mismong pa-pasok ng db (inserts?) pero di ko mapagana yung pagsubmit ng form para makuha yung parameter values
