### ISSUE TITLE
NOTIFICATION MODAL HEADER

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#34]
![screen shot 2016-10-16 at 4 18 12 pm](https://cloud.githubusercontent.com/assets/11243128/19417042/7caf0510-93d4-11e6-9408-28ba8336e992.png)

pati ung ibaba meron

-ITAdminjsImports.js
-ajaxIntegrate.js
-forums.js
-comments.js

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19418473/1c4b3946-93f7-11e6-9e9c-7589af42d28b.png)
Done! What I did is change style na lang. 

![image](https://cloud.githubusercontent.com/assets/11292448/19418484/34616da2-93f7-11e6-9c29-265aa77e2ba8.png)
