### ISSUE TITLE
Loading Spinner reports library

### ISSUE THREAD

**Issue by grcldq** [Shermaine98/projectTEK2#36]
spinner for reports library save to pdf

**Comment by Shermaine98** [comment]
working on it...

with this, hindi ko lang siya mapagana ng maayos.. can you check may codes na ako.. tatag ko d2 after push

https://github.com/Xportability/css-to-pdf/issues/28 @gcla109

**Comment by gcla109** [comment]
noet yet working on mine... @Shermaine98

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19618317/8d0b27d2-9879-11e6-84cd-4cb66ba39de9.png)

 ito ba yun? @Shermaine98 , other than that nothing else happens

**Comment by Shermaine98** [comment]
![screen shot 2016-10-23 at 9 45 39 pm](https://cloud.githubusercontent.com/assets/11243128/19626723/23641cca-996a-11e6-9a9b-c72846c642c0.png)

@gcla109  check this. may effect siya.. ung spinner LOL kaso ang bilis
