### ISSUE TITLE
New Topic Button FORUM

### ISSUE THREAD

**Issue by grcldq** [Shermaine98/projectTEK2#37]
Nothing is happening at mine for now...

**Comment by Shermaine98** [comment]
may ginawa ka ba d2 na codes other than layouts? login servlet, maybe? @gcla109

**Comment by grcldq** [comment]
wala

**Comment by Shermaine98** [comment]
fixed this pero may weird error sa console need to double check....  @gcla109  further investigation needed

**Comment by grcldq** [comment]
Tried it! Walang lumalabas sa akin :)
