### ISSUE TITLE
PUBLISHED REPORTS IMAGE

### ISSUE THREAD

**Issue by grcldq** [Shermaine98/projectTEK2#40]
![image](https://cloud.githubusercontent.com/assets/11292448/19627633/b9054516-997d-11e6-9838-81250c7fedd7.png)

this happens sa image sa matrix report!! omg pero ok naman yung sa integrated analysis

**Comment by Shermaine98** [comment]
@gcla109 try to debug..

**Comment by gcla109** [comment]
di ko mapagana ung base64
