### ISSUE TITLE
Database Population - accounts report

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#43]

**Comment by grcldq** [comment]
Ano to??

**Comment by Shermaine98** [comment]
lagyan lng ng laman ung database ng account 
report for 2013, 2014, 2015

**Comment by grcldq** [comment]
Howw?

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19929294/a2fc7f74-a13d-11e6-93b0-3db917215794.png)

uploaded na to DB > Updated
