### ISSUE TITLE
Demographics - Transaction

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#47]
upload with error, note errors should be not more than 3
_________________
reject all

**Comment by Shermaine98** [comment]
(arrTempError.size() > 3) tama ito d ba?

**Comment by Shermaine98** [comment]
d na ako nakakapagisip

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19925350/9138af6e-a12a-11e6-9a91-2f4e902b07f3.png)

edited: dinisplay:none ko yung mga 1 na nakalagay sa reason. oh btw walang commas yung thousand numbers... @Shermaine98 

![image](https://cloud.githubusercontent.com/assets/11292448/19925745/403789f8-a12c-11e6-9056-3844603db090.png)
(Reason: None) only appears in Edit saved report not directly while validation

Missing fields nakalagay -1
Kaya ba naka-maroon color yung error?
but nagssubmit na lahat

**Comment by grcldq** [comment]
Rejecting works, Mag push lang ako then pull mo na lang @Shermaine98

**Comment by Shermaine98** [comment]
ah tom ko pa aayusin yan. goods lang

**Comment by grcldq** [comment]
ok na ba to? close na lang if done na/
