### ISSUE TITLE
Reports Library Printing Pagination

### ISSUE THREAD

**Issue by grcldq** [Shermaine98/projectTEK2#6]
What I have tried:
@page (iba ibang style)
Stackoverflow solutions (merong isa na nagwwork but problem is sa last page lang lumalabas, aka after all tables may nakalagay doon Page 1)
Seen princexml and something else but is used through command line

**Comment by Shermaine98** [comment]
@gcla109  http://stackoverflow.com/questions/20050939/print-page-numbers-on-pages-when-printing-html did u try this one?

**Comment by Shermaine98** [comment]
https://davidwalsh.name/css-page-breaks

**Comment by Shermaine98** [comment]
will try this tom saving all the links here

**Comment by grcldq** [comment]
Yuuuh lahat ng nasa stackoverflow triny ko di gumagana

**Comment by Shermaine98** [comment]
hmm if wala talga we might need to go jasper hahaha @gcla109  HMMMMM how to do this
