### ISSUE TITLE
"No available report"

### ISSUE THREAD

**Issue by gianroxas** [Shermaine98/projectTEK2#65]
Display a "no available report" for years that are not existing in the database (reports internal and published)

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19996237/15d23654-a299-11e6-8b53-ba5c645249a3.png)

Working: 
Published Reports - Analysis and Matrix (ayaw sa integrated for some reason)
not working in internal. same code should be working. ayw gumana ng style display block and none @gianroxas @Shermaine98 test

**Comment by Shermaine98** [comment]
ahmm inalis mo ung modal?

**Comment by Shermaine98** [comment]
@gcla109 inalis mo ung modal?

**Comment by grcldq** [comment]
ohh what modal? hindi lumabas sa akin @Shermaine98 
nag cancel push ako nung may lumabas na conflicts eh pero kung working lahat sayo pabalik na lang codes mo

**Comment by Shermaine98** [comment]
ahhhh d ko pa kasi na tetest ung ginawa ko kanina pero sige..

**Comment by Shermaine98** [comment]
![image](https://cloud.githubusercontent.com/assets/11243128/20000413/464c18cc-a2b2-11e6-89f0-1e3e34d69c56.png)

**Comment by Shermaine98** [comment]
![image](https://cloud.githubusercontent.com/assets/11243128/20002468/03d803a2-a2bc-11e6-9ca9-81832725d9a0.png)

okay na ung modal ko @gcla109

**Comment by Shermaine98** [comment]
natatandtad

**Comment by Shermaine98** [comment]
okay lang din yan..pero pa emtpy
