### ISSUE TITLE
Published Report

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#70]
napansin ko kagabi parang walang report title

**Comment by grcldq** [comment]
Feel ko sayo lang yan?? kasi sa akin meron lahat

![image](https://cloud.githubusercontent.com/assets/11292448/19992877/6284c5ec-a27c-11e6-8535-6055b43fd5da.png)

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/19992884/78f0dcd0-a27c-11e6-9ccb-bd597b6ffa03.png)

check mo saan ka nawawalan

**Comment by Shermaine98** [comment]
nope sa print pag na pprint

**Comment by Shermaine98** [comment]
@gcla109

**Comment by grcldq** [comment]
ok pa din sa akin

**Comment by Shermaine98** [comment]
may title ung print?

**Comment by Shermaine98** [comment]
![image](https://cloud.githubusercontent.com/assets/11243128/19994474/a7eb3ee2-a289-11e6-8d87-1eb934a8b7f5.png)
