### ISSUE TITLE
Populate Forum

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#71]
kindly pupulate ung forum db

at least 3 hot topics then lagyan na rin ng mga comments :D

**Comment by grcldq** [comment]
@gianroxas pwede ikaw na lang dito?? huhu wala ako maisip ilagay na may bearing

**Comment by gianroxas** [comment]
Sure @gcla109 no probs! 👍

**Comment by gianroxas** [comment]
Done. Please download this db https://drive.google.com/a/dlsu.edu.ph/file/d/0By9hfBxX-G8DeW1XY3NxMXVjam8/view?usp=sharing
