### ISSUE TITLE
nawala ung spinner :(

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#74]
![screen shot 2016-11-05 at 12 05 27 am](https://cloud.githubusercontent.com/assets/11243128/20012805/ab9f154c-a2eb-11e6-972b-baf614459686.png)

**Comment by Shermaine98** [comment]
@gcla109  pa try ito mabalick if kaya

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/20090532/a39caffa-a5c8-11e6-9129-b804cddf07e4.png)

yung spinner for print lang ata talaga??

**Comment by grcldq** [comment]
@Shermaine98

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/20092006/c40de1b6-a5d0-11e6-9202-4c60dd64eb94.png)
 ganito na lang
