### ISSUE TITLE
kaya ba ma center ito ng maayos?

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#75]
![image](https://cloud.githubusercontent.com/assets/11243128/20047043/4960d68e-a4eb-11e6-8274-fcf494502bd8.png)

d gumagana

                    $(para2).append('<center><img style="width: 90%; margin-top:5%; margin-bottom: 2%;" id="image"  src="' + dataURL + '"></center>');

**Comment by grcldq** [comment]
hindi eh triny ko na to before icenter ganyan sya talaga :(
