### ISSUE TITLE
Profile Modal not found

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#8]
![screen shot 2016-09-28 at 10 17 35 pm](https://cloud.githubusercontent.com/assets/11243128/18917168/7dca13ea-85c9-11e6-9537-2ee96a787f17.png)

**Comment by Shermaine98** [comment]
check it sa others home pages wala naman ung error @gcla109

**Comment by grcldq** [comment]
baka sa import. levelOfAccess.jsp lang sa iba eh

**Comment by grcldq** [comment]
pinush ko, pacheck na lang if dun pa error, di lumalabas sa akin eh haha @Shermaine98 pinalitan ko lang ung sa import ng levelofaccess.
