### ISSUE TITLE
pa lakihan ung table or paano papagkasyahin ito

### ISSUE THREAD

**Issue by Shermaine98** [Shermaine98/projectTEK2#80]
![image](https://cloud.githubusercontent.com/assets/11243128/20127026/a8c70040-a675-11e6-9aee-b1ee34f19a78.png)

**Comment by grcldq** [comment]
![image](https://cloud.githubusercontent.com/assets/11292448/20141304/b0ecfc70-a6ca-11e6-83d7-03b7b58489d0.png)

needs zooming out, and then patanggal null values? :)
