### ISSUE TITLE
Editable textboxes

### ISSUE THREAD

**Issue by gianroxas** [Shermaine98/projectTEK2#82]
Naging editable nanaman yung textboxes ng Internal Reports huhu

**Comment by Shermaine98** [comment]
paano na fix ito dati? d ko matrack sa issues na close walng naka link

**Comment by gianroxas** [comment]
@Shermaine98 hindi ko na nilagyan ng textbox yung tables. Then, yung format(), ginawa ko siyang .text, instead of .val.

**Comment by gianroxas** [comment]
Okay na to
