### ISSUE TITLE
Create Report Image Issue

### ISSUE THREAD

**Issue by grcldq** [Shermaine98/projectTEK2#84]
![image](https://cloud.githubusercontent.com/assets/11292448/20247264/04788cf2-aa03-11e6-9b11-2835a4873a39.png)

error in creating report,
pag nag create report (what i tried was demo matrix), pag inadd chart, iba yung image na lumalabas not the one i chose in the pivot table. di ko alam saan niya nakukuha yun

**Comment by grcldq** [comment]
btw wala akong ginalaw sa pivot table

**Comment by gianroxas** [comment]
Sa HighCharts ata nakuha yung image?

**Comment by Shermaine98** [comment]
@gianroxas  kindly double check this. (weird bug ito, intermittent) 

NOTE: dont commit any picutres

**Comment by gianroxas** [comment]
@Shermaine98 sige check ko, naka-commit ata ako ng images dati.

**Comment by gianroxas** [comment]
@Shermaine98 @gcla109 nagdelete na ako ng mga images sa latest push ko.
