### ISSUE TITLE
After save report, no image appears

### ISSUE THREAD

**Issue by grcldq** [Shermaine98/projectTEK2#91]
![image](https://cloud.githubusercontent.com/assets/11292448/20460183/1fbd8f8a-af17-11e6-91cb-e403c40a7c99.png)

**Comment by Shermaine98** [comment]
try this on windows

**Comment by Shermaine98** [comment]
![image](https://cloud.githubusercontent.com/assets/11243128/20471278/51ff95ea-afeb-11e6-947a-1c8442d3d8a3.png)

ito lang ba dapat ung laman, fixed this and pushed if not please fix @gianroxas  @gcla109

**Comment by Shermaine98** [comment]
@gcla109  test this. dapat okay na create a report to check if may nasira thanks
